recipes:
  - "cookbooks/functions/default.rb"
  - "cookbooks/homebrew/default.rb"
  - "cookbooks/vim/default.rb"
  - "cookbooks/jq/default.rb"
  - "cookbooks/peco/default.rb"
  - "cookbooks/ghq/default.rb"
  - "cookbooks/tree/default.rb"
  - "cookbooks/tmux/default.rb"
  - "cookbooks/awscli/default.rb"
  - "cookbooks/ecspresso/default.rb"
  - "cookbooks/iterm2/default.rb"
  - "cookbooks/visual-studio-code/default.rb"
  - "cookbooks/docker-desktop/default.rb"
